image:
  name: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.4:v1.0.0"

variables:
  TF_ROOT: ${CI_PROJECT_DIR}  # The relative path to the root directory of the Terraform project
  TF_STATE_NAME: default      # The name of the state file used by the GitLab Managed Terraform state backend

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

validate: &terraform_validate
  stage: validate
  script:
    - gitlab-terraform validate
  when:
    manual















stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - validate

# build-job:       # This job runs in the build stage, which runs first.
#   stage: build
#   script:
#     - echo "Compiling the code..."
#     - echo "$CI_PROJECT_ID $CI_PIPELINE_ID"
#     - echo "Compile complete."