stages:          # List of stages for jobs, and their order of execution
  - build
#   - test
  - deploy



build-job/getting-branch-name:
  stage: build
  only:
    - dev/backend/test
  script:
    - echo "Getting branch name..."
    - echo $CI_COMMIT_BRANCH
    - read SERVICE_NAME < <(echo $CI_COMMIT_BRANCH | sed 's/dev\/backend\///')
    - echo "SERVICE NAME is $SERVICE_NAME"
    - export SERVICE_NAME

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  needs: ["build-job/getting-branch-name"]
  only:
    - dev/backend/test
  before_script:
    - echo $CI_COMMIT_BRANCH
    - read SERVICE_NAME < <(echo $CI_COMMIT_BRANCH | sed 's/dev\/backend\///')
  script:
    - echo "Compiling the code..."
    - chmod +x gradlew
    - ./gradlew clean bootJar
    - docker build -t itmagician/b305-vuddy-$SERVICE_NAME:$CI_COMMIT_SHA .
    - docker tag itmagician/b305-vuddy-$SERVICE_NAME:$CI_COMMIT_SHA itmagician/b305-vuddy-$SERVICE_NAME
    - docker push itmagician/b305-vuddy-$SERVICE_NAME:$CI_COMMIT_SHA
    - docker push itmagician/b305-vuddy-$SERVICE_NAME
    - echo "Compile complete."

build-job/deploy-argo-cd:       # This job runs in the build stage, which runs first.
  stage: build
  needs: ["build-job"]
  only:
    - dev/backend/test
  before_script:
    - echo $CI_COMMIT_BRANCH
    - read SERVICE_NAME < <(echo $CI_COMMIT_BRANCH | sed 's/dev\/backend\///')
    - echo "https://${CI_USERNAME}:${CI_TOKEN}@lab.ssafy.com/s08-final/S08P31B305.git"
    - git clone "https://${CI_USERNAME}:${CI_TOKEN}@lab.ssafy.com/s08-final/S08P31B305.git" "${CI_COMMIT_SHA}"
    - git config --global user.email "${GIT_USER_EMAIL:-$CI_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$CI_USERNAME}"
    - cd "${CI_COMMIT_SHA}"
    - git checkout devops/kubernetes/helm-chart
    - ls -R .
  script:
    - yq e -i '.backend.auth.image.tag = env(CI_COMMIT_SHA)' backendImages-values.yaml
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
    - git add .
    - git commit -m "$CI_COMMIT_BRANCH is updated"
    - git push origin devops/kubernetes/helm-chart -o ci.skip

