stages:          # List of stages for jobs, and their order of execution
  - build
#   - test
  - deploy



build-job/getting-branch-name:
  stage: build
  # only:
  #   - devops/cicd-script/backend
  # rules:
  #   - if: '$CI_COMMIT_REF_NAME =~ /^dev\/backend/'
  script:
    - echo "Getting branch name..."
    - echo $CI_COMMIT_BRANCH
    - read SERVICE_NAME < <(echo $CI_COMMIT_BRANCH | sed 's/dev\/backend\///')
    - echo "SERVICE NAME is $SERVICE_NAME"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  # only:
  #   - devops/cicd-script/backend
  # rules:
  #   - if: '$CI_COMMIT_REF_NAME =~ /^dev\/backend/'
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
