stages:
  - prepare

init:
  stage: prepare
  tags:
    - shell
  script:
    - echo "Hello World"


# image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
# variables:
#   TF_ROOT: ${CI_PROJECT_DIR}
#   TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}

# cache:
#   key: example-production
#   paths:
#     - ${TF_ROOT}/.terraform

# before_script:
#   - cd ${TF_ROOT}

# stages:
#   - prepare
#   - validate
#   - build
#   - deploy

# init:
#   stage: prepare
#   script:
#     - gitlab-terraform init









# build-job:       # This job runs in the build stage, which runs first.
#   stage: build
#   script:
#     - echo "Compiling the code..."
#     - echo "$CI_PROJECT_ID $CI_PIPELINE_ID"
#     - echo "Compile complete."