stages:          # List of stages for jobs, and their order of execution
  - build
  # - test
  - deploy

build-job/tmp:       # This job runs in the build stage, which runs first.
  stage: build
  only:
    - develop
  script:
    - echo "Compiling the code..."
    - cd server/server1
    - chmod +x gradlew
    - ./gradlew clean bootJar
    - docker build -t itmagician/b305-buddy:test .
    - echo "Compile complete."

deploy-job/tmp/clean:
  stage: deploy
  environment: production
  only:
    - develop
  needs: ["build-job/tmp"]
  allow_failure: true
  when: on_success
  script:
    - docker container stop tmp 
    - docker container rm tmp

deploy-job/tmp/deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - develop
  needs: ["deploy-job/tmp/clean"]
  when: on_success
  script:
    - echo "Deploying application..."
    - docker run --name tmp -p 9001:8080 -d itmagician/b305-buddy:test
    - echo "Application successfully deployed."
