# Default values for vuddy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  auth:
    image:
      pullPolicy: Always
      tag: "5de24dcade1ff67b3c098fc566f2e0504170bdf1"
  user:
    image:
      pullPolicy: Always
      tag: "a94f1e6ec76103f5c4fc0ee699542c49f2e386e3"
  feed:
    image:
      pullPolicy: Always
      tag: "0baf91aa537cb7e8fffaff9aaa59d6f5daea0445"
  friend:
    image:
      pullPolicy: Always
      tag: "92ab0edff1a10ff713ce8d59381a92be09962bbd"
  comment:
    image:
      pullPolicy: Always
      tag: "df916f6a376237f71d192589322d6accec541c33"
  location:
    image:
      pullPolicy: Always
      tag: "6ba576488c768bd984dc67d0533a1f978fc007df"
  chatting:
    image:
      pullPolicy: Always
      tag: "6fe8cf24952843955819452f2b5dc9664bb5594a"
  test:
    image:
      tag: "aa2eded109ec9043c9f3abac6787a1631ab8be5f"
