
server:
  port: 8080
  context-path: /myapp

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/buddy-db
    username: root
    password: abcd1234
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chatting
    producer:
      bootstrap-servers: localhost:9092
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1