
server:
  port: 8080
  context-path: /chatting

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/vuddy}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:abcd1234}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9092}
      group-id: chatting
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9092}

