
server:
  port: 8080
  context-path: /chatting

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/vuddy}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:abcd1234}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9092}
      group-id: chatting
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9092}
logging:
  file:
    name: /log/spring/chat/chat.log  # 로깅 파일 위치이다.
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    root: INFO
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB