version: '3.5'
services:
  mysql:
    image: itmagician/b305-vuddy-mysql
    restart: always
    cap_add:
      - SYS_NICE
    # container_name: mysql-servver # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - MYSQL_USER=${MYSQL_USERNAME:-ssafy}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-ssafy}
      - MYSQL_DATABASE=vuddy # default 생성 DB Schema
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-ssafy}
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=1000

    volumes:
      - ./mysql/data:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    command: '--requirepass b305b305'
    ports:
      - "6379:6379"


