apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatting
  namespace: {{ .Values.Namespace }}
  labels:
    app: chatting
spec:
  selector:
    matchLabels:
      app: chatting
  replicas: {{ .Values.backend.chatting.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chatting
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: chatting
          {{ if (empty .Values.backend.chatting.image.tag) }}
          image: itmagician/b305-vuddy-chatting
          {{ else }}
          image: {{ printf "itmagician/b305-vuddy-chatting:%s" .Values.backend.chatting.image.tag }}
          {{ end }}
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          readinessProbe:
            httpGet:
              path: /chatting/opened/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /chatting/opened/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 30
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysql.url }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: REDIS_HOST_NAME
              value: {{ .Values.redis.url }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: KAFKA_HOST_NAME
              value: {{ printf "%s" .Values.kafka.hostname }}
          ports:
            - containerPort: 8080
      restartPolicy: {{ .Values.backend.chatting.image.pullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: chatting-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: chatting
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: chatting-svc
      protocol: TCP
      port: 80
      targetPort: 8080
