apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  namespace: {{ .Release.Namespace }}
  labels:
    app: comment
spec:
  selector:
    matchLabels:
      app: comment
  replicas: {{ .Values.backend.comment.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          {{ if (empty .Values.backend.comment.image.tag) }}
          image: itmagician/b305-vuddy-comment
          {{ else }}
          image: {{ printf "itmagician/b305-vuddy-comment:%s" .Values.backend.comment.image.tag }}
          {{ end }}
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            # httpGet:
            #   path: /comment/opened/health
            #   port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /comment/opened/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 30


          env:
            - name: MYSQL_URL
              value: {{ .Values.mysql.url }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - containerPort: 8080
      restartPolicy: {{ .Values.backend.comment.image.pullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: comment-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: comment
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: comment-svc
      protocol: TCP
      port: {{ .Values.ingress.port }}
      targetPort: 8080
