# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vuddy-no-auth-ing
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.org/websocket-services: "location-svc,chatting-svc"
    nginx.ingress.kubernetes.io/proxy-read-timeout: 300
    nginx.ingress.kubernetes.io/proxy-body-size: "100mb"
spec:
  ingressClassName: nginx
  rules:
    - {{ if or (eq .Release.Namespace "default") (.Release.Namespace | lower | eq  "production") }}
      host: www.vuddy.co.kr
      {{ else }}
      host: {{.Release.Namespace}}.vuddy.co.kr
      {{ end }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 80
          - path: /user/opened
            pathType: Prefix
            backend:
              service:
                name: user-svc
                port:
                  number: 80
          - path: /feed/opened
            pathType: Prefix
            backend:
              service:
                name: feed-svc
                port:
                  number: 80
          - path: /friend/opened
            pathType: Prefix
            backend:
              service:
                name: friend-svc
                port:
                  number: 80
          - path: /comment/opened
            pathType: Prefix
            backend:
              service:
                name: comment-svc
                port:
                  number: 80
          - path: /location
            pathType: Prefix
            backend:
              service:
                name: location-svc
                port:
                  number: 80
          - path: /chatting
            pathType: Prefix
            backend:
              service:
                name: chatting-svc
                port:
                  number: 80
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: test-svc
                port:
                  number: 80
