apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: {{ .Release.Namespace }}
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: {{ .Values.backend.user.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          {{ if (empty .Values.backend.user.image.tag) }}
          image: itmagician/b305-vuddy-user
          {{ else }}
          image: {{ printf "itmagician/b305-vuddy-user:%s" .Values.backend.user.image.tag }}
          {{ end }}
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          livenessProbe:
            httpGet:
              path: /user/opened/health
              port: 8080
          #   initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysql.url }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - containerPort: 8080
      restartPolicy: {{ .Values.backend.user.image.pullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: user
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: user-svc
      protocol: TCP
      port: 80
      targetPort: 8080
